PIPELINE_CSS = {}
PIPELINE_CSS['docviewer-base'] = {
    'source_filenames': (
        'docviewer/css/components/reset.css',
        'docviewer/css/components/structure.css',
        'docviewer/css/components/ui.css',
        'docviewer/css/components/annotations.css',
        'docviewer/css/components/pages.css',
        'docviewer/css/components/ui-header.css',
        'docviewer/css/components/ui-footer.css',
        'docviewer/css/components/ui-menu.css',
        'docviewer/css/components/ui-navigation.css',
        'docviewer/css/components/ui-search.css',
        'docviewer/css/components/ui-text.css',
        'docviewer/css/vendor/jquery-ui-1.9.2.css',
        'docviewer/css/components/ui-zoom.css',
        'docviewer/css/components/view-annotations.css',
        'docviewer/css/components/view-document.css',
        'docviewer/css/components/view-search.css',
        'docviewer/css/components/view-text.css',
        'docviewer/css/components/view-thumbnails.css',
        'docviewer/css/components/unsupported.css',
        'docviewer/css/components/minimode.css',

        'docviewer/css/themes/plain.css',
        ),
    'output_filename': 'c/docviewer-base.r?.css',
}

PIPELINE_CSS['docviewer-print'] = {
    'source_filenames': (
        'docviewer/css/print.css',
        ),
    'extra_context': {
        'media': 'print',
    },
    'output_filename': 'c/docviewer-print.r?.css',
}
PIPELINE_JS = {}
PIPELINE_JS['docviewer-template'] = {
    'source_filenames': (
        'docviewer/js/views/annotation.jst',
        'docviewer/js/views/annotationNav.jst',
        'docviewer/js/views/chapterNav.jst',
        'docviewer/js/views/descriptionContainer.jst',
        'docviewer/js/views/footer.jst',
        'docviewer/js/views/fullscreenControl.jst',
        'docviewer/js/views/header.jst',
        'docviewer/js/views/navControls.jst',
        'docviewer/js/views/navigationExpander.jst',
        'docviewer/js/views/pageAnnotation.jst',
        'docviewer/js/views/pages.jst',
        'docviewer/js/views/thumbnails.jst',
        'docviewer/js/views/unsupported.jst',
        'docviewer/js/views/viewer.jst',
        'docviewer/js/editor/editor.js',
    ),
    'output_filename': 'c/docviewer-template.r?.js',
}
PIPELINE_JS['docviewer-base'] = {
    'source_filenames': (
        'docviewer/js/vendor/jquery-1.5.1.js',
        'docviewer/js/vendor/jquery-ui.1.9.2.js',
        'docviewer/js/vendor/underscore.js',
        'docviewer/js/vendor/jquery.acceptInput.js',
        'docviewer/js/vendor/jquery.placeholder.js',
        'docviewer/js/lib/initializer.js',
        'docviewer/js/lib/history.js',
        'docviewer/js/lib/annotation.js',
        'docviewer/js/lib/drag_reporter.js',
        'docviewer/js/lib/elements.js',
        'docviewer/js/lib/page.js',
        'docviewer/js/lib/page_set.js',
        'docviewer/js/lib/thumbnails.js',
        'docviewer/js/schema/schema.js',
        'docviewer/js/elements/elements.js',
        'docviewer/js/models/annotation.js',
        'docviewer/js/models/chapter.js',
        'docviewer/js/models/document.js',
        'docviewer/js/models/page.js',
        'docviewer/js/events/events.js',
        'docviewer/js/events/ViewAnnotation.js',
        'docviewer/js/events/ViewDocument.js',
        'docviewer/js/events/ViewSearch.js',
        'docviewer/js/events/ViewText.js',
        'docviewer/js/events/ViewThumbnails.js',
        'docviewer/js/events/history.js',
        'docviewer/js/events/navigation.js',
        'docviewer/js/helpers/helpers.js',
        'docviewer/js/helpers/annotations.js',
        'docviewer/js/helpers/construction.js',
        'docviewer/js/helpers/editor.js',
        'docviewer/js/helpers/navigation.js',
        'docviewer/js/helpers/search.js',
        'docviewer/js/states/states.js',
        'docviewer/js/controllers/document_viewer.js',
        'docviewer/js/controllers/api.js',
    ),
    'output_filename': 'c/docviewer-base.r?.js',
}

